### ISSUE TITLE
Performance of MVI

### ISSUE THREAD

**Issue by markreg** [notacatjs/dommit#10]
I was just wondering what the performance difference between the MVI pattern: http://futurice.com/blog/reactive-mvc-and-the-virtual-dom/ and dommit's pattern was.

The MVI pattern seems to be more cumbersome than dommit's simple pattern.

Thanks

**Comment by defunctzombie** [comment]
I haven't done any major benchmarks but could be interesting to see.

Another thing worth noting is that we currently don't use `requestAnimationFrame` and that could help dommit perf.

**Comment by markreg** [comment]
Yeah, it'd be interesting to see how https://github.com/joelrich/citojs + https://github.com/Raynos/main-loop/ perform on thousands of nodes vs reactive/dommit.
