### ISSUE TITLE
Differences from component/reactive

### ISSUE THREAD

**Issue by markreg** [notacatjs/dommit#9]
Just curious to know what the differences between dommit and component/reactive are in terms of api or other reasons why dommit was forked from component/reactive.

I was working on a component/reactive app and I saw the latest issue on that repo which stated that you were now maintaining a fork of it called dommit.

Thanks!

**Comment by defunctzombie** [comment]
Mostly naming annoyances honestly. There are so many libs with the "react" this or "react" that name that I wanted to avoid confusion.

I also wanted to introduce some breaking changes and some folks were using component to build and that didn't support versions so it would break their stuff. This repo doesn't use component, only npm and browserify like tooling.

**Comment by markreg** [comment]
Sounds good. I'm using `duo` so dommit should work fine.
